version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./robectron-app/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./robectron-app
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./robectron-app/api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/database

  frontend:
    build:
      context: ./robectron-store
      dockerfile: Dockerfile
    user: node
    ports:
      - "3000:3000"
    volumes:
      - ./robectron-store:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - backend

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  postgres-data:
  caddy_data:
  caddy_config:
